/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/GymGirl.glb 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function GymBro(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('../../models/GymGirl.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group)
  console.log(names)
    useEffect(() => {
        actions[names[6]].reset().fadeIn(0.5).play();
    }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="fitGirl" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig8Hips} />
          <skinnedMesh name="Ch07_Body" geometry={nodes.Ch07_Body.geometry} material={materials.Ch07_body} skeleton={nodes.Ch07_Body.skeleton} />
          <skinnedMesh name="Ch07_Eyelashes" geometry={nodes.Ch07_Eyelashes.geometry} material={materials.Ch07_hair} skeleton={nodes.Ch07_Eyelashes.skeleton} />
          <skinnedMesh name="Ch07_Hair" geometry={nodes.Ch07_Hair.geometry} material={materials.Ch07_hair} skeleton={nodes.Ch07_Hair.skeleton} />
          <skinnedMesh name="Ch07_Heels" geometry={nodes.Ch07_Heels.geometry} material={materials.Ch07_body} skeleton={nodes.Ch07_Heels.skeleton} />
          <skinnedMesh name="Ch07_Pants" geometry={nodes.Ch07_Pants.geometry} material={materials.Ch07_body} skeleton={nodes.Ch07_Pants.skeleton} />
          <skinnedMesh name="Ch07_Shirt" geometry={nodes.Ch07_Shirt.geometry} material={materials.Ch07_body} skeleton={nodes.Ch07_Shirt.skeleton} />
          <skinnedMesh name="Ch07_Suit" geometry={nodes.Ch07_Suit.geometry} material={materials.Ch07_body} skeleton={nodes.Ch07_Suit.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../models/GymGirl.glb')
