/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/James.glb 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function James(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('../../models/James.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group)
  console.log(names)
    useEffect(() => {
        actions[names[6]].reset().fadeIn(0.5).play();
    }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="James" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig9Hips} />
          <group name="Ch06">
            <skinnedMesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials.Ch06_body} skeleton={nodes.Mesh.skeleton} />
            <skinnedMesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.Ch06_eyelashes} skeleton={nodes.Mesh_1.skeleton} />
            <skinnedMesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={materials.Ch06_body1} skeleton={nodes.Mesh_2.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../models/James.glb')
